#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mlt
Version  : 6.18.0
Release  : 7
URL      : https://github.com/mltframework/mlt/releases/download/v6.18.0/mlt-6.18.0.tar.gz
Source0  : https://github.com/mltframework/mlt/releases/download/v6.18.0/mlt-6.18.0.tar.gz
Summary  : An open source multimedia framework
Group    : Development/Tools
License  : LGPL-2.1 MIT
Requires: mlt-bin = %{version}-%{release}
Requires: mlt-data = %{version}-%{release}
Requires: mlt-lib = %{version}-%{release}
Requires: mlt-license = %{version}-%{release}
BuildRequires : SDL2-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-cpan
BuildRequires : buildreq-qmake
BuildRequires : fftw-dev
BuildRequires : glibc-dev
BuildRequires : gtk+-dev
BuildRequires : libxml2-dev
BuildRequires : opencv-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(fftw3)
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(libavcodec)
BuildRequires : pkgconfig(libavdevice)
BuildRequires : pkgconfig(libavfilter)
BuildRequires : pkgconfig(libavutil)
BuildRequires : pkgconfig(libexif)
BuildRequires : pkgconfig(libpulse-simple)
BuildRequires : pkgconfig(libswresample)
BuildRequires : pkgconfig(libswscale)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(sdl2)
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtsvg-dev
BuildRequires : sox-dev

%description
--------------------
Written by Charles Yates <charles.yates@pandora.be>
and Dan Dennedy <dan@dennedy.org>

%package bin
Summary: bin components for the mlt package.
Group: Binaries
Requires: mlt-data = %{version}-%{release}
Requires: mlt-license = %{version}-%{release}

%description bin
bin components for the mlt package.


%package data
Summary: data components for the mlt package.
Group: Data

%description data
data components for the mlt package.


%package dev
Summary: dev components for the mlt package.
Group: Development
Requires: mlt-lib = %{version}-%{release}
Requires: mlt-bin = %{version}-%{release}
Requires: mlt-data = %{version}-%{release}
Provides: mlt-devel = %{version}-%{release}
Requires: mlt = %{version}-%{release}
Requires: mlt = %{version}-%{release}

%description dev
dev components for the mlt package.


%package lib
Summary: lib components for the mlt package.
Group: Libraries
Requires: mlt-data = %{version}-%{release}
Requires: mlt-license = %{version}-%{release}

%description lib
lib components for the mlt package.


%package license
Summary: license components for the mlt package.
Group: Default

%description license
license components for the mlt package.


%prep
%setup -q -n mlt-6.18.0
cd %{_builddir}/mlt-6.18.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1574442628
mkdir -p clr-build
pushd clr-build
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1574442628
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mlt
cp %{_builddir}/mlt-6.18.0/COPYING %{buildroot}/usr/share/package-licenses/mlt/3704f4680301a60004b20f94e0b5b8c7ff1484a9
cp %{_builddir}/mlt-6.18.0/src/modules/plus/ebur128/COPYING %{buildroot}/usr/share/package-licenses/mlt/2627ff03833f74ed51a7f43c55d30b249b6a0707
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/melt

%files data
%defattr(-,root,root,-)
/usr/share/mlt/avformat/blacklist.txt
/usr/share/mlt/avformat/consumer_avformat.yml
/usr/share/mlt/avformat/producer_avformat.yml
/usr/share/mlt/core/consumer_multi.yml
/usr/share/mlt/core/data_fx.properties
/usr/share/mlt/core/filter_audiomap.yml
/usr/share/mlt/core/filter_audiowave.yml
/usr/share/mlt/core/filter_brightness.yml
/usr/share/mlt/core/filter_channelcopy.yml
/usr/share/mlt/core/filter_crop.yml
/usr/share/mlt/core/filter_data_show.yml
/usr/share/mlt/core/filter_fieldorder.yml
/usr/share/mlt/core/filter_gamma.yml
/usr/share/mlt/core/filter_greyscale.yml
/usr/share/mlt/core/filter_luma.yml
/usr/share/mlt/core/filter_mask_apply.yml
/usr/share/mlt/core/filter_mask_start.yml
/usr/share/mlt/core/filter_mirror.yml
/usr/share/mlt/core/filter_mono.yml
/usr/share/mlt/core/filter_obscure.yml
/usr/share/mlt/core/filter_panner.yml
/usr/share/mlt/core/filter_region.yml
/usr/share/mlt/core/filter_rescale.yml
/usr/share/mlt/core/filter_resize.yml
/usr/share/mlt/core/filter_transition.yml
/usr/share/mlt/core/filter_watermark.yml
/usr/share/mlt/core/loader.dict
/usr/share/mlt/core/loader.ini
/usr/share/mlt/core/producer_colour.yml
/usr/share/mlt/core/producer_consumer.yml
/usr/share/mlt/core/producer_hold.yml
/usr/share/mlt/core/producer_loader.yml
/usr/share/mlt/core/producer_melt.yml
/usr/share/mlt/core/producer_melt_file.yml
/usr/share/mlt/core/producer_noise.yml
/usr/share/mlt/core/producer_timewarp.yml
/usr/share/mlt/core/producer_tone.yml
/usr/share/mlt/core/transition_composite.yml
/usr/share/mlt/core/transition_luma.yml
/usr/share/mlt/core/transition_matte.yml
/usr/share/mlt/core/transition_mix.yml
/usr/share/mlt/core/transition_region.yml
/usr/share/mlt/decklink/consumer_decklink.yml
/usr/share/mlt/decklink/producer_decklink.yml
/usr/share/mlt/feeds/NTSC/data_fx.properties
/usr/share/mlt/feeds/NTSC/etv.properties
/usr/share/mlt/feeds/NTSC/obscure.properties
/usr/share/mlt/feeds/PAL/border.properties
/usr/share/mlt/feeds/PAL/data_fx.properties
/usr/share/mlt/feeds/PAL/etv.properties
/usr/share/mlt/feeds/PAL/example.properties
/usr/share/mlt/feeds/PAL/obscure.properties
/usr/share/mlt/gtk2/consumer_gtk2_preview.yml
/usr/share/mlt/gtk2/filter_rescale.yml
/usr/share/mlt/gtk2/producer_pango.yml
/usr/share/mlt/gtk2/producer_pixbuf.yml
/usr/share/mlt/kdenlive/filter_boxblur.yml
/usr/share/mlt/kdenlive/filter_freeze.yml
/usr/share/mlt/kdenlive/filter_wave.yml
/usr/share/mlt/kdenlive/producer_framebuffer.yml
/usr/share/mlt/mltplusgpl/consumer_cbrts.yml
/usr/share/mlt/mltplusgpl/filter_burningtv.yml
/usr/share/mlt/mltplusgpl/filter_lumaliftgaingamma.yml
/usr/share/mlt/mltplusgpl/filter_rotoscoping.yml
/usr/share/mlt/motion_est/filter_autotrack_rectangle.yml
/usr/share/mlt/motion_est/filter_motion_est.yml
/usr/share/mlt/motion_est/filter_vismv.yml
/usr/share/mlt/motion_est/producer_slowmotion.yml
/usr/share/mlt/normalize/filter_audiolevel.yml
/usr/share/mlt/normalize/filter_volume.yml
/usr/share/mlt/oldfilm/filter_dust.yml
/usr/share/mlt/oldfilm/filter_grain.yml
/usr/share/mlt/oldfilm/filter_lines.yml
/usr/share/mlt/oldfilm/filter_oldfilm.yml
/usr/share/mlt/oldfilm/filter_tcolor.yml
/usr/share/mlt/oldfilm/filter_vignette.yml
/usr/share/mlt/plus/consumer_blipflash.yml
/usr/share/mlt/plus/filter_affine.yml
/usr/share/mlt/plus/filter_charcoal.yml
/usr/share/mlt/plus/filter_dance.yml
/usr/share/mlt/plus/filter_dynamic_loudness.yml
/usr/share/mlt/plus/filter_dynamictext.yml
/usr/share/mlt/plus/filter_fft.yml
/usr/share/mlt/plus/filter_invert.yml
/usr/share/mlt/plus/filter_lift_gamma_gain.yml
/usr/share/mlt/plus/filter_loudness.yml
/usr/share/mlt/plus/filter_loudness_meter.yml
/usr/share/mlt/plus/filter_lumakey.yml
/usr/share/mlt/plus/filter_rgblut.yml
/usr/share/mlt/plus/filter_sepia.yml
/usr/share/mlt/plus/filter_spot_remover.yml
/usr/share/mlt/plus/filter_text.yml
/usr/share/mlt/plus/filter_timer.yml
/usr/share/mlt/plus/producer_blipflash.yml
/usr/share/mlt/plus/producer_count.yml
/usr/share/mlt/plus/transition_affine.yml
/usr/share/mlt/qt/filter_audiospectrum.yml
/usr/share/mlt/qt/filter_audiowaveform.yml
/usr/share/mlt/qt/filter_lightshow.yml
/usr/share/mlt/qt/filter_qtblend.yml
/usr/share/mlt/qt/filter_qtext.yml
/usr/share/mlt/qt/producer_kdenlivetitle.yml
/usr/share/mlt/qt/producer_qimage.yml
/usr/share/mlt/qt/producer_qtext.yml
/usr/share/mlt/qt/transition_qtblend.yml
/usr/share/mlt/qt/transition_vqm.yml
/usr/share/mlt/rtaudio/consumer_rtaudio.yml
/usr/share/mlt/sdl2/consumer_sdl2.yml
/usr/share/mlt/sdl2/consumer_sdl2_audio.yml
/usr/share/mlt/vmfx/filter_chroma.yml
/usr/share/mlt/vmfx/filter_chroma_hold.yml
/usr/share/mlt/vmfx/filter_mono.yml
/usr/share/mlt/vmfx/filter_shape.yml
/usr/share/mlt/vmfx/producer_pgm.yml
/usr/share/mlt/xml/consumer_xml.yml
/usr/share/mlt/xml/mlt-xml.dtd
/usr/share/mlt/xml/producer_xml-nogl.yml
/usr/share/mlt/xml/producer_xml-string.yml
/usr/share/mlt/xml/producer_xml.yml

%files dev
%defattr(-,root,root,-)
/usr/include/mlt++/Mlt.h
/usr/include/mlt++/MltAnimation.h
/usr/include/mlt++/MltConfig.h
/usr/include/mlt++/MltConsumer.h
/usr/include/mlt++/MltDeque.h
/usr/include/mlt++/MltEvent.h
/usr/include/mlt++/MltFactory.h
/usr/include/mlt++/MltField.h
/usr/include/mlt++/MltFilter.h
/usr/include/mlt++/MltFilteredConsumer.h
/usr/include/mlt++/MltFilteredProducer.h
/usr/include/mlt++/MltFrame.h
/usr/include/mlt++/MltGeometry.h
/usr/include/mlt++/MltMultitrack.h
/usr/include/mlt++/MltParser.h
/usr/include/mlt++/MltPlaylist.h
/usr/include/mlt++/MltProducer.h
/usr/include/mlt++/MltProfile.h
/usr/include/mlt++/MltProperties.h
/usr/include/mlt++/MltPushConsumer.h
/usr/include/mlt++/MltRepository.h
/usr/include/mlt++/MltService.h
/usr/include/mlt++/MltTokeniser.h
/usr/include/mlt++/MltTractor.h
/usr/include/mlt++/MltTransition.h
/usr/include/mlt/mlt.h
/usr/include/mlt/mlt_animation.h
/usr/include/mlt/mlt_cache.h
/usr/include/mlt/mlt_consumer.h
/usr/include/mlt/mlt_deque.h
/usr/include/mlt/mlt_events.h
/usr/include/mlt/mlt_factory.h
/usr/include/mlt/mlt_field.h
/usr/include/mlt/mlt_filter.h
/usr/include/mlt/mlt_frame.h
/usr/include/mlt/mlt_geometry.h
/usr/include/mlt/mlt_log.h
/usr/include/mlt/mlt_luma_map.h
/usr/include/mlt/mlt_multitrack.h
/usr/include/mlt/mlt_parser.h
/usr/include/mlt/mlt_playlist.h
/usr/include/mlt/mlt_pool.h
/usr/include/mlt/mlt_producer.h
/usr/include/mlt/mlt_profile.h
/usr/include/mlt/mlt_properties.h
/usr/include/mlt/mlt_property.h
/usr/include/mlt/mlt_repository.h
/usr/include/mlt/mlt_service.h
/usr/include/mlt/mlt_slices.h
/usr/include/mlt/mlt_tokeniser.h
/usr/include/mlt/mlt_tractor.h
/usr/include/mlt/mlt_transition.h
/usr/include/mlt/mlt_types.h
/usr/include/mlt/mlt_version.h
/usr/lib64/libmlt++.so
/usr/lib64/libmlt.so
/usr/lib64/pkgconfig/mlt++.pc
/usr/lib64/pkgconfig/mlt-framework.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmlt++.so.3
/usr/lib64/libmlt.so.6
/usr/lib64/libmlt.so.6.17.0
/usr/lib64/mlt/libmltavformat.so
/usr/lib64/mlt/libmltcore.so
/usr/lib64/mlt/libmltdecklink.so
/usr/lib64/mlt/libmltgtk2.so
/usr/lib64/mlt/libmltkdenlive.so
/usr/lib64/mlt/libmltmotion_est.so
/usr/lib64/mlt/libmltnormalize.so
/usr/lib64/mlt/libmltoldfilm.so
/usr/lib64/mlt/libmltplus.so
/usr/lib64/mlt/libmltplusgpl.so
/usr/lib64/mlt/libmltqt.so
/usr/lib64/mlt/libmltrtaudio.so
/usr/lib64/mlt/libmltsdl2.so
/usr/lib64/mlt/libmltvmfx.so
/usr/lib64/mlt/libmltxine.so
/usr/lib64/mlt/libmltxml.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mlt/2627ff03833f74ed51a7f43c55d30b249b6a0707
/usr/share/package-licenses/mlt/3704f4680301a60004b20f94e0b5b8c7ff1484a9
